### ISSUE TITLE
Здесь всё работает?

### ISSUE THREAD

**Issue by YAMER1** [EduardRe/DebianLikeBitrixVM#13]
Пока никто не задавал вопросы и не писал отзывы, значит я буду первым. А вопросы я задавать люблю.
В теме VMBitrix 9.0.0 некоторые пишут, что вы сделали всё лучше, чем команда бестолковых разработчиков 1C Bitrix, что у вас нету никаких проблем. Это правда? 
Уточните, пожалуйста:
1. У вас корректно работает мультисайтовость, симлинки?
2. Корректно работает Push and Pull.
3. Версия PHP 8.3
4. Поддерживается Nginx + php-fpm или только Apache.
5. Работа с файлами и сайтами также через пользователя Bitrix?
Проверяли все эти пункты, сайт корректно работает?

**Comment by EduardRe** [comment]
Здравствуйте, проблем нет, все работает четко, но если столкнетесь, то можете написать в чат в телеграме и вам помогут
1. У вас корректно работает мультисайтовость, симлинки? - Да, все необходимое создается автоматически
2. Корректно работает Push and Pull. - Да, корректно работает
3. Версия PHP 8.3 - Да, смена версий PHP тоже сделана, причем подтягиваются в реальном времени из репозитория и вы можете выбрать любую версию (не ниже 5.6), которая вам подходит
4. Поддерживается Nginx + php-fpm или только Apache. - Да Nginx + Apache2 + отдача статики через brotli из коробки + поддержка композита из коробки
5. Работа с файлами и сайтами также через пользователя Bitrix? - Нет, тут стандартный пользователь www-data
Проверяли все эти пункты, сайт корректно работает? - Да, конечно проверяли, многие используют мое решение и проблем нет, а если и появляются, то милости прошу в чат поддержки - обязательно поможем
